// <auto-generated />
using System;
using Lamie.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lamie.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731153542_RemoveAllForeignKeyConstraints")]
    partial class RemoveAllForeignKeyConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lamie.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_categories");

                    b.ToTable("md_categories", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_category_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_md_category_translations_language_code");

                    b.HasIndex("CategoryId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_md_category_translations_category_id_language_code");

                    b.ToTable("md_category_translations", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sales_channels");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_channels_code");

                    b.HasIndex("SortOrder", "Name")
                        .HasDatabaseName("ix_sales_channels_sort_order_name");

                    b.ToTable("sales_channels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "admin",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Admin",
                            SortOrder = 10,
                            UpdatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "website",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Website",
                            SortOrder = 20,
                            UpdatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "phone",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Phone",
                            SortOrder = 30,
                            UpdatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "walk-in",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Walk-in",
                            SortOrder = 40,
                            UpdatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "social",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Social",
                            SortOrder = 50,
                            UpdatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_collections");

                    b.ToTable("md_collections", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.CollectionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int")
                        .HasColumnName("collection_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_collection_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_md_collection_translations_language_code");

                    b.HasIndex("CollectionId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_md_collection_translations_collection_id_language_code");

                    b.ToTable("md_collection_translations", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hex_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RgbCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rgb_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_colors");

                    b.ToTable("md_colors", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ColorTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_color_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_md_color_translations_language_code");

                    b.HasIndex("ColorId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_md_color_translations_color_id_language_code");

                    b.ToTable("md_color_translations", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_crm_customers");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_crm_customers_created_at");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_crm_customers_normalized_email")
                        .HasFilter("[normalized_email] IS NOT NULL");

                    b.HasIndex("NormalizedPhone")
                        .HasDatabaseName("ix_crm_customers_normalized_phone");

                    b.ToTable("crm_customers", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Code")
                        .HasName("pk_sys_languages");

                    b.ToTable("sys_languages", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Occasion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_occasions");

                    b.ToTable("md_occasions", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.OccasionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("OccasionId")
                        .HasColumnType("int")
                        .HasColumnName("occasion_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_occasion_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_md_occasion_translations_language_code");

                    b.HasIndex("OccasionId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_md_occasion_translations_occasion_id_language_code");

                    b.ToTable("md_occasion_translations", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentNote")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("content_note");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("delivery_address");

                    b.Property<string>("DeliveryAddressDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("delivery_address_description");

                    b.Property<DateTime>("DeliveryAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("delivery_at");

                    b.Property<decimal?>("DeliveryLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("delivery_latitude");

                    b.Property<decimal?>("DeliveryLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("delivery_longitude");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_total");

                    b.Property<bool>("InventoryReserved")
                        .HasColumnType("bit")
                        .HasColumnName("inventory_reserved");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("order_code");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int")
                        .HasColumnName("order_status");

                    b.Property<string>("OrdererName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("orderer_name");

                    b.Property<string>("OrdererPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("orderer_phone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("payment_status");

                    b.Property<bool>("PickupAtShop")
                        .HasColumnType("bit")
                        .HasColumnName("pickup_at_shop");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("recipient_phone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_fee");

                    b.Property<decimal?>("ShippingFeeActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_fee_actual");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sub_total");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_orders");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_sales_orders_created_at");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_sales_orders_created_by_id");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_orders_order_code");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_sales_orders_updated_by_id");

                    b.HasIndex("ChannelId", "CreatedAt")
                        .HasDatabaseName("ix_sales_orders_channel_id_created_at");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .HasDatabaseName("ix_sales_orders_customer_id_created_at");

                    b.HasIndex("DeliveryAt", "OrderStatus")
                        .HasDatabaseName("ix_sales_orders_delivery_at_order_status");

                    b.HasIndex("OrderStatus", "CreatedAt")
                        .HasDatabaseName("ix_sales_orders_order_status_created_at");

                    b.HasIndex("PaymentStatus", "CreatedAt")
                        .HasDatabaseName("ix_sales_orders_payment_status_created_at");

                    b.ToTable("sales_orders", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.OrderChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("change_type");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("changed_by_id");

                    b.Property<string>("ChangedByName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("changed_by_name");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("new_value");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("note");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("old_value");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_order_change_logs");

                    b.HasIndex("ChangedById")
                        .HasDatabaseName("ix_sales_order_change_logs_changed_by_id");

                    b.HasIndex("OrderId", "ChangedAt")
                        .HasDatabaseName("ix_sales_order_change_logs_order_id_changed_at");

                    b.ToTable("sales_order_change_logs", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.OrderImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_item_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_sales_order_images");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_sales_order_images_order_item_id");

                    b.HasIndex("OrderId", "SortOrder")
                        .HasDatabaseName("ix_sales_order_images_order_id_sort_order");

                    b.ToTable("sales_order_images", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductSku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("product_sku");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("thumbnail_url");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_sales_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sales_order_items_product_id");

                    b.ToTable("sales_order_items", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sku");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail_url");

                    b.Property<bool>("TracksInventory")
                        .HasColumnType("bit")
                        .HasColumnName("tracks_inventory");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_cat_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_cat_products_category_id");

                    b.HasIndex("ProductTypeId")
                        .HasDatabaseName("ix_cat_products_product_type_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_cat_products_sku");

                    b.HasIndex("IsActive", "Stock")
                        .HasDatabaseName("ix_cat_products_is_active_stock");

                    b.ToTable("cat_products", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int")
                        .HasColumnName("collection_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_rel_product_collections");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_rel_product_collections_collection_id");

                    b.HasIndex("ProductId", "CollectionId")
                        .IsUnique()
                        .HasDatabaseName("ix_rel_product_collections_product_id_collection_id");

                    b.ToTable("rel_product_collections", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_rel_product_colors");

                    b.HasIndex("ColorId")
                        .HasDatabaseName("ix_rel_product_colors_color_id");

                    b.HasIndex("ProductId", "ColorId")
                        .IsUnique()
                        .HasDatabaseName("ix_rel_product_colors_product_id_color_id");

                    b.ToTable("rel_product_colors", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_cat_product_images");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_cat_product_images_product_id");

                    b.ToTable("cat_product_images", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductOccasion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<int>("OccasionId")
                        .HasColumnType("int")
                        .HasColumnName("occasion_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_rel_product_occasions");

                    b.HasIndex("OccasionId")
                        .HasDatabaseName("ix_rel_product_occasions_occasion_id");

                    b.HasIndex("ProductId", "OccasionId")
                        .IsUnique()
                        .HasDatabaseName("ix_rel_product_occasions_product_id_occasion_id");

                    b.ToTable("rel_product_occasions", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("StyleId")
                        .HasColumnType("int")
                        .HasColumnName("style_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_rel_product_styles");

                    b.HasIndex("StyleId")
                        .HasDatabaseName("ix_rel_product_styles_style_id");

                    b.HasIndex("ProductId", "StyleId")
                        .IsUnique()
                        .HasDatabaseName("ix_rel_product_styles_product_id_style_id");

                    b.ToTable("rel_product_styles", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_rel_product_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_rel_product_tags_tag_id");

                    b.HasIndex("ProductId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("ix_rel_product_tags_product_id_tag_id");

                    b.ToTable("rel_product_tags", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_cat_product_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_cat_product_translations_language_code");

                    b.HasIndex("ProductId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_cat_product_translations_product_id_language_code");

                    b.ToTable("cat_product_translations", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_product_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_md_product_types_code");

                    b.ToTable("md_product_types", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_product_type_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_md_product_type_translations_language_code");

                    b.HasIndex("ProductTypeId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_md_product_type_translations_product_type_id_language_code");

                    b.ToTable("md_product_type_translations", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_auth_refresh_tokens_user_id_expires_at");

                    b.ToTable("auth_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_styles");

                    b.ToTable("md_styles", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.StyleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("StyleId")
                        .HasColumnType("int")
                        .HasColumnName("style_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_style_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_md_style_translations_language_code");

                    b.HasIndex("StyleId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_md_style_translations_style_id_language_code");

                    b.ToTable("md_style_translations", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_tags");

                    b.ToTable("md_tags", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.TagTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_name");

                    b.HasKey("Id")
                        .HasName("pk_md_tag_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_md_tag_translations_language_code");

                    b.HasIndex("TagId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_md_tag_translations_tag_id_language_code");

                    b.ToTable("md_tag_translations", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_auth_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_users_normalized_user_name");

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("Lamie.Domain.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Category", null)
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_md_category_translations_md_categories_category_id");

                    b.HasOne("Lamie.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_md_category_translations_sys_languages_language_code");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.CollectionTranslation", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Collection", null)
                        .WithMany("Translations")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_md_collection_translations_md_collections_collection_id");

                    b.HasOne("Lamie.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_md_collection_translations_sys_languages_language_code");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ColorTranslation", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Color", null)
                        .WithMany("Translations")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_md_color_translations_md_colors_color_id");

                    b.HasOne("Lamie.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_md_color_translations_sys_languages_language_code");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.OccasionTranslation", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_md_occasion_translations_sys_languages_language_code");

                    b.HasOne("Lamie.Domain.Entities.Occasion", null)
                        .WithMany("Translations")
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_md_occasion_translations_md_occasions_occasion_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Order", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_orders_sales_channels_channel_id");

                    b.HasOne("Lamie.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_orders_auth_users_created_by_id");

                    b.HasOne("Lamie.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_orders_crm_customers_customer_id");

                    b.HasOne("Lamie.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_orders_auth_users_updated_by_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.OrderChangeLog", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_order_change_logs_auth_users_changed_by_id");

                    b.HasOne("Lamie.Domain.Entities.Order", null)
                        .WithMany("ChangeLogs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_change_logs_sales_orders_order_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.OrderImage", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Order", null)
                        .WithMany("Images")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_images_sales_orders_order_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_items_sales_orders_order_id");

                    b.HasOne("Lamie.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_order_items_products_product_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Product", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cat_products_categories_category_id");

                    b.HasOne("Lamie.Domain.Entities.ProductType", null)
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cat_products_product_types_product_type_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductCollection", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_collections_collections_collection_id");

                    b.HasOne("Lamie.Domain.Entities.Product", null)
                        .WithMany("Collections")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_collections_cat_products_product_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductColor", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_colors_colors_color_id");

                    b.HasOne("Lamie.Domain.Entities.Product", null)
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_colors_cat_products_product_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cat_product_images_cat_products_product_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductOccasion", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_occasions_occasions_occasion_id");

                    b.HasOne("Lamie.Domain.Entities.Product", null)
                        .WithMany("Occasions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_occasions_cat_products_product_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductStyle", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Product", null)
                        .WithMany("Styles")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_styles_cat_products_product_id");

                    b.HasOne("Lamie.Domain.Entities.Style", null)
                        .WithMany()
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_styles_styles_style_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductTag", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Product", null)
                        .WithMany("Tags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_tags_cat_products_product_id");

                    b.HasOne("Lamie.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rel_product_tags_tags_tag_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductTranslation", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cat_product_translations_sys_languages_language_code");

                    b.HasOne("Lamie.Domain.Entities.Product", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cat_product_translations_cat_products_product_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductTypeTranslation", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_md_product_type_translations_sys_languages_language_code");

                    b.HasOne("Lamie.Domain.Entities.ProductType", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_md_product_type_translations_md_product_types_product_type_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_refresh_tokens_auth_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.StyleTranslation", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_md_style_translations_sys_languages_language_code");

                    b.HasOne("Lamie.Domain.Entities.Style", null)
                        .WithMany("Translations")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_md_style_translations_md_styles_style_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.TagTranslation", b =>
                {
                    b.HasOne("Lamie.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_md_tag_translations_sys_languages_language_code");

                    b.HasOne("Lamie.Domain.Entities.Tag", null)
                        .WithMany("Translations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_md_tag_translations_md_tags_tag_id");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Category", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Color", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Occasion", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Order", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("Images");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Product", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Colors");

                    b.Navigation("Images");

                    b.Navigation("Occasions");

                    b.Navigation("Styles");

                    b.Navigation("Tags");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.ProductType", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Style", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Lamie.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
